[package]
name    = "icon-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
image = { version = "0.25", default-features = false, features = [
    "png",
    "jpeg",
] }
ico = "0.3"
icns = "0.3"
anyhow = "1.0"
